language: node_js
node_js: 
 - 10.15.2

install:
  - yarn add newman
  - yarn

env:
  matrix:
    - MONGOURL=$MONGOURL
    - CI=$CI

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version